challenges/urls.py
from django.urls import include, path
from . import views
from .views import (
    ChallengeMainView,
    ChallengeCreateView,
    ChallengeUpdateView,
    ChallengeDeleteView,
    ChallengeOverviewView,
    ChallengeDataView,
    ChallengeRulesView,
    ChallengeSolutionsView
)

urlpatterns = [
    path('', ChallengeMainView.as_view(), name='challenges_main'),
    path('<int:pk>/', ChallengeOverviewView.as_view(), name='challenges_detail'),
    path('create/', ChallengeCreateView.as_view(), name='challenges_create'),
    path('<challengeid>/participate', views.participate_in_challenge, name='participate'),
    path('<challengeid>/leavechallenge', views.leave_challenge, name='leave'),
    path('<int:pk>/update', ChallengeUpdateView.as_view(), name='challenges_update'),
    path('<int:pk>/delete', ChallengeDeleteView.as_view(), name='challenges_delete'),
    path('<int:pk>/overview', ChallengeOverviewView.as_view(), name='challenges_overview'),
    path('<int:pk>/data', ChallengeDataView.as_view(), name='challenges_data'),
    path('<int:pk>/solutions', ChallengeSolutionsView.as_view(), name='challenges_solutions'),
    path('<int:pk>/rules', ChallengeRulesView.as_view(), name='challenges_rules')

]

main/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.main, name="main-page"),
]

nhs_pg/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.views.static import serve
# from . import views
from django.conf.urls import url
from ckeditor_uploader import views as uploader_views
from django.views.decorators.cache import never_cache

urlpatterns = [
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^ckeditor/upload/',
        uploader_views.upload, name='ckeditor_upload'),
    url(r'^ckeditor/browse/',
        never_cache(uploader_views.browse), name='ckeditor_browse'),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('challenges/', include('challenges.urls')),
    path('solutions/', include('solutions.urls')),
    path('discussion/', include('discussion.urls')),
    path('tutorial/', include('tutorial.urls')),
    path('register/', user_views.RegisterView.as_view(), name='register'),
    path('profile/<username>', user_views.specific_profile, name='specific_profile'),
    path('profile/', user_views.profile, name='profile'),
    path('register/developer/', user_views.DeveloperRegisterView.as_view(), name='developer_register'),
    path('register/clinician/', user_views.ClinicianRegisterView.as_view(), name='clinician_register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

challenges/models.py
from django.db import models
from django.utils import timezone
from users.models import Developer, Clinician
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Challenge(models.Model):
    title = models.CharField(max_length=100)
    brief = models.CharField(max_length=200, default="")
    date_created = models.DateTimeField(default=timezone.now)
    # award = RichTextUploadingField(blank=True)
    award = models.IntegerField(verbose_name= ('Target cost saving in GBP'), default=0, blank=True, validators=[MaxValueValidator(1000000000)])
    clinician = models.ForeignKey(Clinician, on_delete=models.CASCADE, related_name="creator")  # clinician who created the challenge
    developers = models.ManyToManyField(Developer, blank=True)  # developerS who indicated interest
    description = RichTextUploadingField(blank=True)
    evaluation = RichTextUploadingField(blank=True)
    timeline = RichTextUploadingField(blank=True)
    rule = RichTextUploadingField(blank=True)
    data = models.FileField(blank=True)

    def get_developers(self):
        return ",".join([str(d) for d in self.developers.all()])

    def __str__(self):
        return f'Challenge: {self.title}'

    def get_absolute_url(self):
        return reverse('challenges_detail', kwargs={'pk': self.pk})

solutions/models.py
from django.db import models
from users.models import Developer
from challenges.models import Challenge
from django.utils import timezone
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Solution(models.Model):
    title = models.CharField(max_length=100, default="")
    date_created = models.DateTimeField(default=timezone.now)
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE, related_name="creator")  # person who solved the person
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)  # challenge the solution is targeting
    description = RichTextUploadingField(blank=True)
    accuracy = models.FloatField(default=0.0)
    solution_data = models.FileField()
    solution_notebook = models.FileField(blank=True)
    solution_notebook_htmlver = models.FileField(blank=True)

    def __str__(self):
        return f'Solution: {self.title}'

    def get_absolute_url(self):
        return reverse('solutions_detail', kwargs={'pk': self.pk})

challenges/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.urls import reverse

from .models import Developer, Challenge
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)


def user_is_participating(challengeid, userid):
    current_challenge = Challenge.objects.get(pk=challengeid)
    for developer in current_challenge.developers.all():
        if developer.pk == userid:
            return True
    return False


def participate_in_challenge(request, challengeid):
    user = Developer.objects.get(user=request.user)
    if not user_is_participating(challengeid, user.pk):
        Challenge.objects.get(pk=challengeid).developers.add(user)
        # return render(request, 'challenges/challenge_list.html')
    return HttpResponseRedirect(reverse('challenges_detail', args=[challengeid]))


def leave_challenge(request, challengeid):
    user = Developer.objects.get(user=request.user)
    if user_is_participating(challengeid, user.pk):
        Challenge.objects.get(pk = challengeid).developers.remove(user)
        # return render(request, 'challenges/challenge_list.html')
    return HttpResponseRedirect(reverse('challenges_detail', args=[challengeid]))


class ChallengeMainView(ListView):
    model = Challenge
    template_name = 'challenges/challenge_list.html'
    context_object_name = 'challenges'
    ordering = ['-date_created']
    paginate_by = 5


class ChallengeOverviewView(DetailView):
    model = Challenge
    template_name = 'challenges/challenge_overview.html'


class ChallengeDataView(DetailView):
    model = Challenge
    template_name = 'challenges/challenge_data.html'


class ChallengeSolutionsView(DetailView):
    model = Challenge
    template_name = 'challenges/challenge_solutions.html'


class ChallengeRulesView(DetailView):
    model = Challenge
    template_name = 'challenges/challenge_rules.html'


class ChallengeCreateView(SuccessMessageMixin, CreateView):
    model = Challenge
    fields = ['title',  'award', 'description', 'data', 'evaluation', 'timeline', 'rule', 'brief']
    success_message = "The challenge has been successfully created."

    def form_valid(self, form):
        form.instance.clinician = self.request.user.clinician
        form.save()
        return super(ChallengeCreateView, self).form_valid(form)


class ChallengeUpdateView(SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    model = Challenge
    fields = ['title',  'award', 'description', 'data', 'evaluation', 'timeline', 'rule', 'brief']
    success_message = "The challenge has been successfully updated."

    def form_valid(self, form):
        form.instance.clinician = self.request.user.clinician
        return super(ChallengeUpdateView, self).form_valid(form)

    def test_func(self):
        challenge = self.get_object()
        try:
            if self.request.user.clinician == challenge.clinician:
                return True
        except AttributeError:
            return False


class ChallengeDeleteView(UserPassesTestMixin, DeleteView):
    model = Challenge
    success_url = '/'
    success_message = 'The challenge has been successfully deleted.'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ChallengeDeleteView, self).delete(request, *args, **kwargs)

    def test_func(self):
        challenge = self.get_object()
        try:
            if self.request.user.clinician == challenge.clinician:
                return True
        except AttributeError:
            return False

challenges/templates/challenges/challenge_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}

    {% if user.is_admin or user.is_clinician %}
        <div class="content-section">
            <form method="post" novalidate>
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Are you sure you want to delete Challenge {{ object.title }} ?
                    </legend>
                    <input type="hidden" name="next" value="{{ next }}">
                </fieldset>
                <div class="form-group">
                    <button type="submit" class="btn btn-danger">Confirm Delete</button>
                    <a class="btn badge-secondary" href="{% url 'challenges_detail' object.id %}"
                       style="margin-left: 2rem">Cancel</a>
                </div>
            </form>
        </div>
    {% else %}
        <legend class="border-bottom mb-4">You are not allowed to modify challenges.</legend>
    {% endif %}
{% endblock %}

challenges/templates/challenges/challenge_data.html
{% extends 'challenges/challenge_detail.html' %}

{% block detailedinfo %}

    <div class="container" style="margin-top: 2rem; padding-left: 0">
        {% if object.data.url != null %}
{#            {% if user.is_admin or user.is_clinician %}#}
                <a class="btn btn-primary" href="{{ object.data.url }}" download>Download Data</a>
{#            {% endif %}#}
            {% else %}
            <h3>No Data Given</h3>
        {% endif %}
    </div>


{% endblock %}

challenges/templates/challenges/challenge_detail.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load template_methods %}

{% block content %}
    <div class="card" style="border-bottom-left-radius: 0; border-bottom-right-radius: 0; margin-top: 2rem">
        <div class="card-body row">
            <div class="col-md-9">
                <h1>{{ object.title }}</h1>
                <p>{{ object.brief }}</p>
                <p class="lead">Created by <a href="
                {% if user == object.clinician.user %}
                    {% url 'profile' %}
                {% else %}
                    {% url 'specific_profile' object.clinician %}
                {% endif %}">{{ object.clinician }}</a> on {{ object.date_created|date:"d F, Y" }}
                </p>
            </div>
            <div class="col-md-3" style="float: right">
                <div style="flex-direction: column;">
                    <h5>Target Cost Saving</h5>
                    <h4>£{{ challenge.award|safe }}</h4>
                    <h6>{{ challenge.developers.all.count }} team(s)</h6>
                </div>
            </div>
        </div>
    </div>


    <div class="card top-rect">
        <ul style="padding-left: 1rem; float: left">
            <li class="masterdetail"><a href="{% url 'challenges_overview' object.pk %}">Overview</a></li>
            <li class="masterdetail"><a href="{% url 'challenges_data' object.pk %}">Data</a></li>
            <li class="masterdetail"><a href="{% url 'challenges_solutions' object.pk %}">Solutions</a></li>
            <li class="masterdetail"><a href="{% url 'challenges_rules' object.pk %}">Rules</a></li>
            {% if user.is_developer %}
                {% user_is_in_challenge object.pk user.developer.pk as userParticipation %}
                {% if userParticipation %}
                    <a class="btn btn-danger btn-lg" href="{% url 'leave' object.id %}" role="button"
                       style="float: right; margin-top: 0.8rem; margin-right: 0.5rem">Leave
                        Challenge</a>
                {% else %}
                    <a class="btn btn-primary btn-lg" href="{% url 'participate' object.id %}"
                       role="button" style="float: right; margin-top: 0.8rem; margin-right: 0.5rem">Participate</a>
                {% endif %}
            {% endif %}
        </ul>

    </div>

    {% block detailedinfo %}
    {% endblock %}


    {% if object.clinician == user.clinician %}
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'challenges_update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'challenges_delete' object.id %}">Delete</a>
        </div>
    {% endif %}

    <hr class="my-4">

    <div>
        {% if userParticipation %}
            <a class="btn btn-info btn-lg" href="http://51.140.73.178/hub/user/{{ user.username }}/lab"
               target="_blank"
               role="button">To Jupyter Notebook</a>
            <a class="btn btn-primary btn-lg" href="{% url 'solutions_create' object.pk %}"
               role="button">Submit Solution</a>

            <hr class="my-4">
        {% endif %}

    </div>

{% endblock %}

challenges/templates/challenges/challenge_form.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-10 offset-md-1">
        {% if user.is_admin or user.is_clinician %}
            <div class="content-section">
                <form enctype="multipart/form-data" method="post" novalidate>
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Create a new challenge</legend>
                        <input type="hidden" name="next" value="{{ next }}">
                        <div class="container" style="margin-top: 2rem; padding-left: 0; margin-bottom: 1rem">

                            {{ form.title|as_crispy_field }}
                            {{ form.brief|as_crispy_field }}

                            <ul class="nav nav-pills">
                                <li class="nav-item"><a data-toggle="tab" class="nav-link show active"
                                                        href="#overview">Overview</a>
                                </li>
                                <li class="nav-item"><a data-toggle="tab" class="nav-link show" href="#data">Data</a>
                                </li>
                                <li class="nav-item"><a data-toggle="tab" class="nav-link show" href="#rule">Rule</a>
                                </li>
                            </ul>

                            <div id="challengeMasterTabContent" class="container challengetabcontent" style="width: 100%">

                                <div id="overview" class="tab-pane fade show active">

                                    <ul class="nav flex-column nav-pills" style="float:left; width: 20%;">
                                        <li class="nav-item"><a data-toggle="tab" class="nav-link nav-link-form show active"
                                                                href="#description">Description</a>
                                        </li>
                                        <li class="nav-item"><a data-toggle="tab" class="nav-link-form nav-link show"
                                                                href="#evaluation">Evaluation</a>
                                        </li>
                                        <li class="nav-item"><a data-toggle="tab" class="nav-link nav-link-form show"
                                                                href="#costsaving">Target saving</a>
                                        </li>
                                        <li class="nav-item"><a data-toggle="tab" class="nav-link nav-link-form show"
                                                                href="#timeline">Timeline</a>
                                        </li>
                                    </ul>


                                    <div id="challengeTabContent" class="container challengecreationtabcontent">

                                        <div id="description" class="tab-pane fade show active">
                                            {{ form.description|as_crispy_field }}
                                        </div>

                                        <div id="evaluation" class="tab-pane fade">
                                            {{ form.evaluation|as_crispy_field }}
                                        </div>

                                        <div id="costsaving" class="tab-pane fade">
                                            {{ form.award|as_crispy_field }}
                                        </div>

                                        <div id="timeline" class="tab-pane fade">
                                            {{ form.timeline|as_crispy_field }}
                                        </div>

                                    </div>

                                </div>

                                <div id="data" class="tab-pane fadee">
                                    {{ form.data|as_crispy_field }}
                                </div>

                                <div id="rule" class="tab-pane fade">
                                    {{ form.rule|as_crispy_field }}
                                </div>


                            </div>


                            <div class="clearfix"></div>
                        </div>
                    </fieldset>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Confirm</button>
                    </div>
                </form>
            </div>
        {% else %}
            <legend class="border-bottom mb-4">You are not allowed to modify challenges.</legend>
        {% endif %}
    </div>
{% endblock %}

challenges/templates/challenges/challenge_list.html
{% extends 'main/base.html' %}

{% block banner %}
    {% load static %}
    <div class="container"
         style="max-height:100px;margin-bottom:2rem;max-width:10000px;height:10rem;background-image: url('{% static "pictures/challenge_bg.jpg" %}')">
        <h1 style="padding:2rem 3.5rem;color:#ffffff" class="display-5"><strong>Challenges</strong></h1>
    </div>
{% endblock %}


{% block content %}


    {% for challenge in challenges %}

        <div class="card mb-2" style="padding: 2rem; flex-direction: row">
            <div style="width: 10%; min-width: 20px;"><img
                    src="{{ challenge.clinician.user.profile.image.url }}" width="100%" height="auto"></div>
            <div class="container">
                <div class="card-subtitle">Challenge created by <a href="
            {% if user == challenge.clinician.user %}
                {% url 'profile' %}
            {% else %}
                {% url 'specific_profile' challenge.clinician %}
            {% endif %}">{{ challenge.clinician }}</a> on {{ challenge.date_created }}</div>
                <div class="card-body" style="padding-left: 0">
                    <h4><a class="card-title"
                           href="{% url 'challenges_detail' challenge.id %}">{{ challenge.title }}</a></h4>
                    <p class="card-text">{{ challenge.brief }}</p>
                </div>
            </div>
            <div style="flex-direction: column; align-self: right; width: 20%">
                <h5>Target Cost Saving</h5>
                <h4>£{{ challenge.award|safe }}</h4>
                <h6>{{ challenge.developers.all.count }} team(s)</h6>
            </div>

        </div>
    {% endfor %}

    {% if is_paginated %}
        <div>
            <ul class="pagination">
                {% if page_obj.has_previous %}

                    <li class="page-item">
                        <a class="page-link" href="?page=1">&laquo;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt;</a>
                    </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                    </li>

                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

challenges/templates/challenges/challenge_overview.html
{% extends 'challenges/challenge_detail.html' %}

{% block detailedinfo %}


    <div class="container" style="margin-top: 2rem; padding-left: 0;padding-right: 0; margin-bottom: 1rem">

        <ul class="nav flex-column nav-pills" style="float:left; width: 10%;min-width: 6rem">
            <li class="nav-item"><a data-toggle="tab" class="nav-link show active" href="#description">Description</a>
            </li>
            <li class="nav-item"><a data-toggle="tab" class="nav-link show" href="#evaluation">Evaluation</a></li>
{#            <li class="nav-item"><a data-toggle="tab" class="nav-link show" href="#costsaving">Target saving</a></li>#}
            <li class="nav-item"><a data-toggle="tab" class="nav-link show" href="#timeline">Timeline</a></li>
        </ul>


        <div id="challengeTabContent" class="jumbotron challengetabcontent" style="overflow: auto;">

            <div id="description" class="tab-pane fade show active">
                {{ object.description|safe }}
            </div>

            <div id="evaluation" class="tab-pane fade">
                {{ object.evaluation|safe }}
            </div>

{#            <div id="costsaving" class="tab-pane fade">#}
{#                {{ object.award|safe }}#}
{#            </div>#}

            <div id="timeline" class="tab-pane fade">
                {{ object.timeline|safe }}

        </div>



    </div>

    <div class="clearfix"></div>

    <script>$(document).ready(function () { //to provide sort function
        $('#solution_table').DataTable();
    });</script>

    <table id="solution_table" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th>Solution</th>
            <th>Date Created</th>
            <th>Accuracy</th>
        </tr>
        </thead>
        <tbody>

        {% for solution in challenge.solution_set.all %}
            <tr>
                <td><a
                        href="{% url 'solutions_detail' solution.id %}">{{ solution.title }}</a> by <a href="
                    {% if user == solution.developer.user %}
                        {% url 'profile' %}
                    {% else %}
                        {% url 'specific_profile' solution.developer %}
                    {% endif %}">{{ solution.developer }}</a>

                </td>
                <td>{{ solution.date_created }}</td>
                <td>{{ solution.accuracy }}%</td>
            </tr>
        {% endfor %}

        </tbody>

    </table>


{% endblock %}

challenges/templates/challenges/challenge_rules.html
{% extends 'challenges/challenge_detail.html' %}

{% block detailedinfo %}

    <div class="jumbotron" style="margin-top: 2rem">
        {{ object.rule|safe }}
    </div>

{% endblock %}

challenges/templates/challenges/challenge_solutions.html
{% extends 'challenges/challenge_detail.html' %}

{% block detailedinfo %}

    <div class="container" style="padding: 0; margin-top: 1rem">

        <script>$(document).ready(function () { //to provide sort function
            $('#solution_table').DataTable();
        });</script>

        <table id="solution_table" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>Solution</th>
                <th>Date Created</th>
                <th>Accuracy</th>
            </tr>
            </thead>
            <tbody>

            {% for solution in challenge.solution_set.all %}
                <tr>
                    <td><a
                            href="{% url 'solutions_detail' solution.id %}">{{ solution.title }}</a> by <a href="
                    {% if user == solution.developer.user %}
                        {% url 'profile' %}
                    {% else %}
                        {% url 'specific_profile' solution.developer %}
                    {% endif %}">{{ solution.developer }}</a>

                    </td>
                    <td>{{ solution.date_created }}</td>
                    <td>{{ solution.accuracy }}%</td>
                </tr>
            {% endfor %}

            </tbody>

        </table>

    </div>

{% endblock %}

challenges/templates/challenges/challenges_developers_detail.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="row" style="width: 87rem; ">
    
    <div class="col">
        <div class="card" style="width: 47rem; height: 43rem;">
        <div class="card-header">
            Challenges
        </div>

        <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
        </div>
    </div>


    <div class="col">
    <div class="card" style="width: 20rem; height: 43rem;">
        <div class="card-header">
            Challenges
        </div>
        <div class="card-body">
            <h5 class="card-title">In progress</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div> 
    </div>

  </div>

{% endblock %}

challenges/templates/challenges/challenges_developers_main.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="row" style="width: 87rem; ">
    
    <div class="col">
        <div class="card" style="width: 47rem; height: 43rem;">
        <div class="card-header">
            Challenges
        </div>

        <div class="card-body" style="overflow:auto;">
            <div class="card-title">
                <h5>Joe Willson</h5>
                <p>Uploaded a challenge 8 hours ago<p>
            </div>
            <hr class="featurette-divider">
            <p class="card-text">This challenge requires you to ...Te dolor scribentur referrentur vim. Vix id torquatos voluptatum. Sea ei ludus dicant minimum, et everti sanctus urbanitas usu. Harum putent percipit no pri, at pri mutat dolore labitur. Dolor principes ius eu, doming doctus euismod cu sit, iusto virtute pericula ea cum. Error populo blandit ei pri..</p>
           <p class="card-text">
Rebum appetere ea mea, petentium maiestatis id pri. Cu sit alterum bonorum, cu omnium sensibus cum. Homero quaerendum suscipiantur te qui. Per at quas mucius.</p>
              <p class="card-text">Et numquam scaevola sea, graeco vocent adipiscing ad eam. Nec an ornatus periculis vituperatoribus. Vidisse persequeris in eam, duo ut habeo suavitate. At ius reque lobortis, ea hinc adhuc quaerendum mei, amet tota persecuti vis ut.</p>
        </div>
        </div>
    </div>


    <div class="col">
    <div class="card" style="width: 20rem; height: 43rem;" >
        <div class="card-header">
           In progress
        </div>
        <div class="card-body">

        <ul style="overflow:auto; height:37rem;width:18rem; list-style-type:none;padding-left:0.2rem;padding-right:0.2rem">
        <li style="margin-bottom:2rem" >
            <h5 class="card-title">Challenge 1</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Continue</a>
        </li>

        <li style="margin-bottom:2rem">
            <h5 class="card-title">Challenge 2</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Continue</a>
        </li>

        <li style="margin-bottom:2rem">
            <h5 class="card-title">Challenge 3</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Continue</a>
        </li>

         <li style="margin-bottom:2rem">
            <h5 class="card-title">Challenge 4</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Continue</a>
        </li>

        </ul> 

        </div>
    </div> 
    </div>

  </div>

{% endblock %}